import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { SessionProvider } from "../src/components/SessionProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Login from "@/src/components/Login";
import ClientProvider from "@/src/components/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session  = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body >
        <header>Header content</header>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ): (
            <>
              <ClientProvider />
              <div>{children}</div>
            </>
          )}

        </SessionProvider>
        <footer>Footer content</footer>
      </body>
    </html>
  );
}
